apiVersion: v1
kind: Service
metadata:
  name: devops-challenge
  labels:
    app: devops-challenge
spec:
  type: {{ .Values.service.type }}
  selector:
    app: devops-challenge
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
